/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hotel.ui;


public class ReportForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportForm.class.getName());

    // Static initializer - runs ONCE when this class is first loaded,
    // before any constructor or method runs. This sets up JasperReports
    // context manually so it doesn't crash trying to scan the classpath.
    static {
        try {
            System.setProperty(
                "net.sf.jasperreports.extensions.registry.class",
                "net.sf.jasperreports.extensions.ListExtensionsRegistry"
            );
        } catch (Exception e) {
            System.out.println("JasperReports init note: " + e.getMessage());
        }
    }
    private String role; // "admin" only gets to see this screen
    public ReportForm(String role) {
        this.role = role;

    // compiles the .jrxml design file into a runnable .jasper file.
    // this only needs to happen once - after the first run, the
    // .jasper file already exists and this line can be removed.
    try {
        net.sf.jasperreports.engine.JasperCompileManager.compileReportToFile(
            "reports/ReservationSummaryReport.jrxml",
            "reports/ReservationSummaryReport.jasper");
    } catch (Exception e) {
        // If compilation fails (e.g. jar missing), just print a note
        // so the app doesn't crash - the error will show in the Output panel
        System.out.println("Report compile note: " + e.getMessage());
    }

        initComponents();
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBanner = new javax.swing.JPanel();
        lblBannerTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnGenerateReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reservation Summary Report - Grand Palm Hotel");
        setBackground(new java.awt.Color(247, 245, 242));
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBanner.setBackground(new java.awt.Color(44, 62, 80));
        pnlBanner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBannerTitle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        lblBannerTitle.setForeground(new java.awt.Color(201, 165, 92));
        lblBannerTitle.setText("Reservation Summary Report");
        pnlBanner.add(lblBannerTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 290, -1));

        getContentPane().add(pnlBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 80));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGenerateReport.setBackground(new java.awt.Color(201, 165, 92));
        btnGenerateReport.setText("View Report");
        btnGenerateReport.addActionListener(this::btnGenerateReportActionPerformed);
        jPanel1.add(btnGenerateReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 690, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // This method is called when the admin clicks "Generate Jasper Report".
// It connects to the database, fills the report with live data from
// the reservation_report_view we created in hotel_db.sql, then opens
// it in JasperReports' built-in print-preview viewer window.
private void generateReport() {
    
    // Run everything on a background thread so the UI doesn't freeze
    // while the database query and report compilation are happening.
    new Thread(() -> {

        // Force JasperReports to use a simple extensions registry instead of
        // scanning the whole classpath for extension config files.
        // This avoids a crash (ExceptionInInitializerError) that happens in
        // plain NetBeans Ant projects that don't use Maven/Spring.
        System.setProperty(
            "net.sf.jasperreports.extensions.registry.class",
            "net.sf.jasperreports.extensions.ListExtensionsRegistry"
        );

        try {
            // Step 1: Get a connection to the hotel_db database using our
            // existing DBConnection utility class.
            java.sql.Connection con = com.hotel.util.DBConnection.getConnection();

            // Step 2: Compile the .jrxml design file into a JasperReport object.
            // We use our own compileReport() helper method (defined below)
            // instead of a single hardcoded path, so it works whether we run
            // from the IDE or from a packaged JAR file.
            net.sf.jasperreports.engine.JasperReport jasperReport =
                compileReport("ReservationSummaryReport.jrxml");

            // Step 3: Fill the compiled report with real data by running its
            // embedded SQL query against our database connection.
            net.sf.jasperreports.engine.JasperPrint jasperPrint =
                net.sf.jasperreports.engine.JasperFillManager
                    .fillReport(jasperReport, new java.util.HashMap<>(), con);

            // Step 4: Show the filled report in a JasperViewer window.
            // This must run on the Swing Event Dispatch Thread (EDT),
            // so we wrap it in invokeLater().
            javax.swing.SwingUtilities.invokeLater(() -> {

                // Create the report viewer window, passing our filled report.
                net.sf.jasperreports.view.JasperViewer viewer =
                    new net.sf.jasperreports.view.JasperViewer(jasperPrint, false);

                // Set a custom window title instead of the default Jasper one.
                viewer.setTitle("Reservation Summary Report - Grand Palm Hotel");

                // Closing this window should only close the report viewer,
                // not the whole application.
                viewer.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);

                // Set a reasonable default window size.
                viewer.setSize(1100, 700);

                // Center the window on the screen.
                viewer.setLocationRelativeTo(null);

                // Make the window visible to the user.
                viewer.setVisible(true);
            });

        } catch (Exception e) {

            // Print the full error details to the NetBeans Output console
            // so we can see exactly what went wrong (not just a short message).
            e.printStackTrace();

            // Also show a simple error popup to the user, on the EDT.
            javax.swing.SwingUtilities.invokeLater(() ->
                javax.swing.JOptionPane.showMessageDialog(
                    null,
                    "Report failed: " + e.getMessage(),
                    "Report Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE)
            );
        }

    }).start(); // Start the background thread we created above
}

// Helper method: finds and compiles the JRXML report file.
// It first tries to load the file as a classpath resource (this works
// both when running inside NetBeans AND when running the packaged JAR,
// because the file lives inside src/com/hotel/report/ and gets copied
// into the compiled classes folder automatically).
// If that fails, it falls back to checking a couple of filesystem paths.
private net.sf.jasperreports.engine.JasperReport compileReport(String jrxmlFile) throws Exception {

    // Try to open the JRXML file as a resource on the classpath.
    // The leading "/" means "start from the root of the classpath",
    // which corresponds to the com/hotel/report/ package folder.
    java.io.InputStream stream =
        getClass().getResourceAsStream("/com/hotel/report/" + jrxmlFile);

    // If the file was found on the classpath, compile it directly from the stream.
    if (stream != null) {
        System.out.println("[Report] Loaded from classpath: /com/hotel/report/" + jrxmlFile);
        return net.sf.jasperreports.engine.JasperCompileManager.compileReport(stream);
    }

    // If the classpath lookup failed, try a couple of filesystem locations
    // as a fallback (useful when running directly inside the IDE).
    java.io.File[] candidates = {
        // Path if running from the project root in NetBeans.
        new java.io.File(System.getProperty("user.dir"), "src/com/hotel/report/" + jrxmlFile),
        // Old location, kept as a last-resort fallback.
        new java.io.File(System.getProperty("user.dir"), "reports/" + jrxmlFile)
    };

    // Loop through each candidate path and use the first one that exists.
    for (java.io.File candidate : candidates) {

        // Convert to an absolute, resolved path (handles any ".." in the path).
        java.io.File resolved = candidate.getCanonicalFile();

        // Log what we're trying, useful for debugging.
        System.out.println("[Report] Trying: " + resolved.getAbsolutePath()
                + " exists=" + resolved.exists());

        // If this file actually exists on disk, compile it from there.
        if (resolved.exists()) {
            return net.sf.jasperreports.engine.JasperCompileManager
                    .compileReport(resolved.getAbsolutePath());
        }
    }

    // If none of the strategies found the file, throw a clear error
    // explaining exactly what we were looking for.
    throw new net.sf.jasperreports.engine.JRException(
        "Cannot find report file: " + jrxmlFile +
        " (tried classpath /com/hotel/report/ and the above folders)"
    );
}
    
    
    private void btnGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportActionPerformed
         generateReport();
    }//GEN-LAST:event_btnGenerateReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReportForm("admin").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateReport;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBannerTitle;
    private javax.swing.JPanel pnlBanner;
    // End of variables declaration//GEN-END:variables
}
