/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hotel.ui;


public class ReportForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportForm.class.getName());

    /**
     * Creates new form ReportForm
     */
    private String role; // "admin" only gets to see this screen
    public ReportForm(String role) {
        this.role = role;
    // compiles the .jrxml design file into a runnable .jasper file.
    // this only needs to happen once - after the first run, the
    // .jasper file already exists and this line can be removed.
    try {
        net.sf.jasperreports.engine.JasperCompileManager.compileReportToFile(
            "reports/ReservationSummaryReport.jrxml",
            "reports/ReservationSummaryReport.jasper");
    } catch (Exception e) {
        // If compilation fails (e.g. jar missing), just print a note
        // so the app doesn't crash - the error will show in the Output panel
        System.out.println("Report compile note: " + e.getMessage());
    }
        initComponents();
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBanner = new javax.swing.JPanel();
        lblBannerTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnGenerateReport = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reservation Summary Report - Grand Palm Hotel");
        setBackground(new java.awt.Color(247, 245, 242));
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBanner.setBackground(new java.awt.Color(44, 62, 80));
        pnlBanner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBannerTitle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        lblBannerTitle.setForeground(new java.awt.Color(201, 165, 92));
        lblBannerTitle.setText("Reservation Summary Report");
        pnlBanner.add(lblBannerTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 290, -1));

        getContentPane().add(pnlBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 80));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGenerateReport.setBackground(new java.awt.Color(201, 165, 92));
        btnGenerateReport.setText("View Report");
        btnGenerateReport.addActionListener(this::btnGenerateReportActionPerformed);
        jPanel1.add(btnGenerateReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 140, 40));

        jButton2.setBackground(new java.awt.Color(227, 224, 218));
        jButton2.setText("Refresh");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 640, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // This method is called when the admin clicks "Generate Jasper Report".
// It connects to the database, fills the report with live data from
// the reservation_report_view we created in hotel_db.sql, then opens
// it in JasperReports' built-in print-preview viewer window.
private void generateReport() {
    try {
        // Step 1: Get the shared database connection (our Singleton)
        java.sql.Connection con = com.hotel.util.DBConnection.getConnection();

        // Step 2: Point to the compiled .jasper file.
        // This path assumes you saved the report file inside a "reports"
        // folder at the root of your project. Adjust if yours is elsewhere.
        String reportPath = "reports/ReservationSummaryReport.jasper";

        // Step 3: Fill the report with data from the database.
        // The report uses this SQL query (same as reservation_report_view):
        //   SELECT res.reservation_id, c.full_name AS customer_name,
        //          cat.category_name AS room_type,
        //          DATEDIFF(res.check_out_date, res.check_in_date) AS days_stayed,
        //          res.total_amount, res.status
        //   FROM reservation res
        //   JOIN customer c ON res.customer_id = c.customer_id
        //   JOIN room r ON res.room_id = r.room_id
        //   JOIN room_category cat ON r.category_id = cat.category_id
        //   ORDER BY res.reservation_id
        net.sf.jasperreports.engine.JasperPrint jasperPrint =
            net.sf.jasperreports.engine.JasperFillManager.fillReport(
                reportPath,
                new java.util.HashMap<>(), // no extra parameters needed
                con);

        // Step 4: Open the report in JasperReports' built-in viewer.
        // The viewer lets the admin see, print, or export to PDF.
        net.sf.jasperreports.view.JasperViewer.viewReport(jasperPrint, false);

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Could not generate report: " + e.getMessage(),
            "Report Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}
    
    
    private void btnGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportActionPerformed
         generateReport();
    }//GEN-LAST:event_btnGenerateReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReportForm("admin").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateReport;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBannerTitle;
    private javax.swing.JPanel pnlBanner;
    // End of variables declaration//GEN-END:variables
}
